logging:
  level:
    root: WARN
    org:
      spring: WARN
    io:
      kgraph: DEBUG

info:
  app:
    name: Kafka Graphs

kafka:
  graphs:
    bootstrapServers: localhost:9092
    zookeeperConnect: localhost:2181
    verticesTopic: vertices
    edgesGroupedBySourceTopic: edges
    solutionSetTopic: solutionSet
    solutionSetStore: solutionStore
    workSetTopic: workSet
    numPartitions: 50
    replicationFactor: 1

management.endpoint.health.show-details: always
management.endpoints.web.exposure.include: '*'
